---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

'''{r}
library(classdata)
library(dplyr)
library(ggplot2)

data(ames)
summary(ames)
head(ames$'Parcel ID')
typeof(ames$'Parcel ID')
str(ames)
head(ames$'Sale Price')
range(ames$'Sale Price', na.rm=TRUE)
'''

1. Inspecting the dataset
Manas:
Parcel ID (Character): String containing a set of numbers to describe a unique ID for each parcel. The string can be a 10 digit ID value beginning with a 0.

Address (Character): String containing the address to which the parcel is addressed to. All address strings are in the form of "Number Street, Ames". They do not have a definite data range as they're strings, but they'll all be within Ames.

Style (Factor): This is a factor variable with 12 levels of strings which describes a different style layout of the house. It's range is between the 12 possible levels.

Occupancy (Factor): This is a factor variable with 4 different levels of strings which describes the amount of people that can live in a home. The ranges are between Condominium Single-Family / Owner Occupied, Townhouse, Two-Family Conversion Two-Family Duplex

Sale Date (Date): This date variable describes the day the house was sold. The range of this variable is between 2017-07-03 and 2022-08-31

Sale Price (Numeric): This variable describes the amount the house was sold in USD. The range of this variable is between 0 and 20,500,000.

Multi Sale (Character):

YearBuilt (Numeric):

Acres (Numeric):

TotalLivingArea (Numeric):

Bedrooms (Numeric):

FinishedBsmtArea (Numeric):

LotArea (Numeric):

AC (Character):

FirePlace (Character):

Neighborhood (Factor):

2. Our main variable of special interest in this dataset is the sale price of the homes

3. 
'''{r}
new_data <- filter(ames, `Sale Price` < 10000000, `Sale Price` > 0)
ggplot(data=ames, aes(x=`Sale Price`)) + geom_histogram(binwidth=8000)

mean(new_data$`Sale Price`)
'''
Since our main variable is numeric, we chose a histogram. Taking a dive into the chart, we can see that the mean price of a home is at \$1,017,479. Majority of the homes are less than \$1,000,000, the mean is skewed due to the few houses which are outliers that are extremely expensive. Taking the outliers > \$1,000,000 out of the equation, the average home is \$241,960.


4. 
Manas:
'''{r}
new_data <- filter(ames, `YearBuilt` > 1500, `Sale Price` > 0, !is.na(`YearBuilt`), !is.na(`Sale Price`), `Sale Price` < 1000000)
ggplot(data=new_data, aes(x=`YearBuilt`, y=`Sale Price`)) + geom_point()
range(ames$YearBuilt)
'''
I picked the YearBuilt variable to see if there's a realationship with the main variable Sale Price. overall range of YearBuilt is 0 to 2022. This data needed some filtering, so the real min data shows the first houses in the dataset are from 1880. I also removed houses that are well over \$1M, as they're houses that which are outliers to the dataset. The mean shows us that the average house was built in 1976. Using a scatterplot, we can see a positive correlation between the YearBuilt and the sales price, as the average house price has continued to rise as the years go on.
